#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    N = int(input())
    m=[]
    for N_itr in range(N):
        firstNameEmailID = input().split()

        firstName = firstNameEmailID[0]

        emailID = firstNameEmailID[1]
        #print(emailID[-10:])
        if emailID[-10:]=="@gmail.com":
            m.append(firstName)
    for i in sorted(m):
        print(i)
